# Generated by Django 4.2.6 on 2023-10-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.TextField()),
                ('name_get', models.TextField()),
                ('loc_post', models.TextField()),
                ('loc_get', models.TextField()),
                ('index_post', models.IntegerField()),
                ('index_get', models.IntegerField()),
                ('type_letter', models.IntegerField()),
                ('weight_letter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.TextField()),
                ('name_get', models.TextField()),
                ('loc_post', models.TextField()),
                ('loc_get', models.TextField()),
                ('index_post', models.IntegerField()),
                ('index_get', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('type_parcel', models.IntegerField()),
                ('weight_letter', models.FloatField()),
            ],
        ),
    ]
